noinst_PROGRAMS =
noinst_PROGRAMS += test-basic
noinst_PROGRAMS += test-inheritance
noinst_PROGRAMS += test-object
noinst_PROGRAMS += test-circular-refs

TEST_PROGS += test-basic
TEST_PROGS += test-inheritance
TEST_PROGS += test-object
TEST_PROGS += test-circular-refs

test_basic_SOURCES = $(top_srcdir)/tests/test-basic.c
test_basic_CPPFLAGS = $(GOBJECT_CFLAGS)
test_basic_LDADD = $(GOBJECT_LIBS) $(top_builddir)/libgvs-1.0.la

test_inheritance_SOURCES = $(top_srcdir)/tests/test-inheritance.c
test_inheritance_CPPFLAGS = $(GOBJECT_CFLAGS)
test_inheritance_LDADD = $(GOBJECT_LIBS) $(top_builddir)/libgvs-1.0.la

test_object_SOURCES = $(top_srcdir)/tests/test-object.c
test_object_CPPFLAGS = $(GOBJECT_CFLAGS)
test_object_LDADD = $(GOBJECT_LIBS) $(top_builddir)/libgvs-1.0.la

test_circular_refs_SOURCES = $(top_srcdir)/tests/test-circular-refs.c
test_circular_refs_CPPFLAGS = $(GOBJECT_CFLAGS)
test_circular_refs_LDADD = $(GOBJECT_LIBS) $(top_builddir)/libgvs-1.0.la

# Vala tests
if ENABLE_VAPIGEN

noinst_PROGRAMS += test-basic-vala

TEST_PROGS += test-basic-vala

test_basic_vala_SOURCES = $(top_srcdir)/tests/test-basic-vala.vala
test_basic_vala_VALAFLAGS = --vapidir $(top_srcdir) --pkg gvs-1.0
test_basic_vala_CPPFLAGS = $(GOBJECT_CFLAGS)
test_basic_vala_LDADD = $(GOBJECT_LIBS) $(top_builddir)/libgvs-1.0.la

endif #enable vala

